# This is a basic workflow to help you get started with Actions

name: figma_update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  repository_dispatch:
    types:[opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        ref: ${{ github.head_ref }}
    - run: npm ci
    - run: npm run build
    - run: npm run figma
    - name: Git Auto Commit
      # You may pin to the exact commit or the version.
      # uses: stefanzweifel/git-auto-commit-action@bbd291750d2526367d915d5197485331dc2d8dc7
      uses: stefanzweifel/git-auto-commit-action@v4.7.2
      with:
        commit_message: updated figma file from GH Action
